import type {
  AppNotification,
  Attendance,
  Candidate,
  Client,
  Company,
  Contract,
  ImageAlert,
  Interview,
  Intervention,
  Invoice,
  Payslip,
  Product,
  Publication,
  Quote,
  Receipt,
  Relance,
  Shift,
  Site,
  SupervisionAgent,
  Task,
  Ticket,
} from "./types";

/* Reference "today" for the demo dataset: 2026-07-03. */

export const CLIENTS: Client[] = [
  {
    id: "c1",
    name: "Port Autonome de Dakar",
    sector: "Portuaire",
    contact: "M. Ndour",
    phone: "+221 33 849 45 45",
    sites: 4,
    monthly: 4200000,
    status: "actif",
    health: 88,
    since: "2023-02-01",
  },
  {
    id: "c2",
    name: "Aéroport AIBD",
    sector: "Aéroportuaire",
    contact: "Mme Diouf",
    phone: "+221 33 877 10 00",
    sites: 3,
    monthly: 3600000,
    status: "actif",
    health: 82,
    since: "2023-06-15",
  },
  {
    id: "c3",
    name: "Ambassade de France",
    sector: "Diplomatique",
    contact: "M. Laurent",
    phone: "+221 33 839 51 00",
    sites: 1,
    monthly: 1875000,
    status: "risque",
    health: 54,
    since: "2022-11-20",
  },
  {
    id: "c4",
    name: "Sonatel (Siège)",
    sector: "Télécom",
    contact: "M. Sy",
    phone: "+221 33 839 90 00",
    sites: 2,
    monthly: 2100000,
    status: "actif",
    health: 91,
    since: "2024-01-10",
  },
  {
    id: "c5",
    name: "BICIS Plateau",
    sector: "Banque",
    contact: "Mme Fall",
    phone: "+221 33 839 03 03",
    sites: 2,
    monthly: 1600000,
    status: "actif",
    health: 79,
    since: "2023-09-05",
  },
  {
    id: "c6",
    name: "Sea Plaza",
    sector: "Centre commercial",
    contact: "M. Gomis",
    phone: "+221 33 869 00 00",
    sites: 1,
    monthly: 1350000,
    status: "actif",
    health: 74,
    since: "2024-03-22",
  },
  {
    id: "c7",
    name: "Ambassade des USA",
    sector: "Diplomatique",
    contact: "Ms. Carter",
    phone: "+221 33 879 40 00",
    sites: 1,
    monthly: 2400000,
    status: "prospect",
    health: 66,
    since: "2026-05-30",
  },
  {
    id: "c8",
    name: "CBAO Indépendance",
    sector: "Banque",
    contact: "M. Ba",
    phone: "+221 33 839 96 96",
    sites: 2,
    monthly: 1500000,
    status: "actif",
    health: 84,
    since: "2023-04-18",
  },
  {
    id: "c9",
    name: "Résidence Almadies",
    sector: "Résidentiel",
    contact: "M. Diagne",
    phone: "+221 77 640 12 12",
    sites: 1,
    monthly: 900000,
    status: "prospect",
    health: 61,
    since: "2026-06-12",
  },
  {
    id: "c10",
    name: "Hôtel Saly (Mbour)",
    sector: "Hôtellerie",
    contact: "Mme Sarr",
    phone: "+221 33 957 20 00",
    sites: 1,
    monthly: 1100000,
    status: "actif",
    health: 77,
    since: "2024-07-01",
  },
];

export const INVOICES: Invoice[] = [
  {
    id: "i1",
    ref: "FAC-2026-058",
    client: "Port Autonome de Dakar",
    amount: 4200000,
    issued: "2026-06-30",
    due: "2026-07-30",
    status: "envoyee",
  },
  {
    id: "i2",
    ref: "FAC-2026-057",
    client: "Aéroport AIBD",
    amount: 3600000,
    issued: "2026-06-30",
    due: "2026-07-30",
    status: "envoyee",
  },
  {
    id: "i3",
    ref: "FAC-2025-041",
    client: "Ambassade de France",
    amount: 1875000,
    issued: "2026-05-31",
    due: "2026-06-15",
    status: "retard",
  },
  {
    id: "i4",
    ref: "FAC-2026-055",
    client: "Sonatel (Siège)",
    amount: 2100000,
    issued: "2026-06-28",
    due: "2026-07-28",
    status: "payee",
  },
  {
    id: "i5",
    ref: "FAC-2026-054",
    client: "BICIS Plateau",
    amount: 1600000,
    issued: "2026-06-27",
    due: "2026-07-27",
    status: "payee",
  },
  {
    id: "i6",
    ref: "FAC-2026-053",
    client: "Sea Plaza",
    amount: 1350000,
    issued: "2026-06-25",
    due: "2026-07-25",
    status: "envoyee",
  },
  {
    id: "i7",
    ref: "FAC-2026-052",
    client: "CBAO Indépendance",
    amount: 1500000,
    issued: "2026-06-20",
    due: "2026-07-05",
    status: "retard",
  },
  {
    id: "i8",
    ref: "FAC-2026-051",
    client: "Hôtel Saly (Mbour)",
    amount: 1100000,
    issued: "2026-06-18",
    due: "2026-07-18",
    status: "payee",
  },
  {
    id: "i9",
    ref: "FAC-2026-059",
    client: "Résidence Almadies",
    amount: 900000,
    issued: "2026-07-02",
    due: "2026-08-02",
    status: "brouillon",
  },
];

export const QUOTES: Quote[] = [
  {
    id: "q1",
    ref: "DEV-2026-031",
    client: "Ambassade des USA",
    amount: 2400000,
    created: "2026-06-28",
    status: "negociation",
  },
  {
    id: "q2",
    ref: "DEV-2026-030",
    client: "Résidence Almadies",
    amount: 900000,
    created: "2026-06-25",
    status: "envoye",
  },
  {
    id: "q3",
    ref: "DEV-2026-029",
    client: "Groupe Kalidou (BTP)",
    amount: 1750000,
    created: "2026-06-22",
    status: "envoye",
  },
  {
    id: "q4",
    ref: "DEV-2026-028",
    client: "Clinique du Cap",
    amount: 1200000,
    created: "2026-06-20",
    status: "signe",
  },
  {
    id: "q5",
    ref: "DEV-2026-027",
    client: "Auchan Sacré-Cœur",
    amount: 1650000,
    created: "2026-06-15",
    status: "brouillon",
  },
  {
    id: "q6",
    ref: "DEV-2026-026",
    client: "Université Cheikh Anta Diop",
    amount: 2900000,
    created: "2026-06-12",
    status: "negociation",
  },
  {
    id: "q7",
    ref: "DEV-2026-025",
    client: "SGBS Almadies",
    amount: 1400000,
    created: "2026-06-08",
    status: "signe",
  },
];

export const CONTRACTS: Contract[] = [
  {
    id: "ct1",
    ref: "CTR-2025-007",
    client: "Port Autonome de Dakar",
    monthly: 4200000,
    start: "2025-07-15",
    end: "2026-07-15",
    status: "expirant",
  },
  {
    id: "ct2",
    ref: "CTR-2024-012",
    client: "Aéroport AIBD",
    monthly: 3600000,
    start: "2024-01-01",
    end: "2027-01-01",
    status: "actif",
  },
  {
    id: "ct3",
    ref: "CTR-2024-018",
    client: "Sonatel (Siège)",
    monthly: 2100000,
    start: "2024-01-10",
    end: "2027-01-10",
    status: "actif",
  },
  {
    id: "ct4",
    ref: "CTR-2023-004",
    client: "Ambassade de France",
    monthly: 1875000,
    start: "2022-11-20",
    end: "2026-07-20",
    status: "expirant",
  },
  {
    id: "ct5",
    ref: "CTR-2023-009",
    client: "BICIS Plateau",
    monthly: 1600000,
    start: "2023-09-05",
    end: "2026-09-05",
    status: "actif",
  },
  {
    id: "ct6",
    ref: "CTR-2024-021",
    client: "CBAO Indépendance",
    monthly: 1500000,
    start: "2023-04-18",
    end: "2026-04-18",
    status: "expire",
  },
];

export const RELANCES: Relance[] = [
  {
    id: "r1",
    ref: "FAC-2025-041",
    client: "Ambassade de France",
    amount: 1875000,
    daysLate: 32,
    stage: "J+30",
  },
  {
    id: "r2",
    ref: "FAC-2026-052",
    client: "CBAO Indépendance",
    amount: 1500000,
    daysLate: 12,
    stage: "J+7",
  },
  {
    id: "r3",
    ref: "FAC-2026-048",
    client: "Groupe Kalidou (BTP)",
    amount: 780000,
    daysLate: 3,
    stage: "J+1",
  },
  {
    id: "r4",
    ref: "FAC-2026-039",
    client: "Auchan Sacré-Cœur",
    amount: 1250000,
    daysLate: 44,
    stage: "J+45",
  },
  {
    id: "r5",
    ref: "FAC-2026-045",
    client: "Clinique du Cap",
    amount: 620000,
    daysLate: 16,
    stage: "J+15",
  },
];

export const SITES: Site[] = [
  {
    id: "s1",
    name: "Port Autonome de Dakar",
    zone: "Dakar — Môle",
    agentsNeeded: 12,
    agentsPresent: 11,
  },
  {
    id: "s2",
    name: "Aéroport AIBD",
    zone: "Diass",
    agentsNeeded: 10,
    agentsPresent: 10,
  },
  {
    id: "s3",
    name: "Ambassade de France",
    zone: "Plateau",
    agentsNeeded: 4,
    agentsPresent: 4,
  },
  {
    id: "s4",
    name: "Siège Sonatel",
    zone: "Plateau",
    agentsNeeded: 6,
    agentsPresent: 5,
  },
  {
    id: "s5",
    name: "BICIS Plateau",
    zone: "Plateau",
    agentsNeeded: 4,
    agentsPresent: 4,
  },
  {
    id: "s6",
    name: "Sea Plaza",
    zone: "Corniche",
    agentsNeeded: 5,
    agentsPresent: 3,
  },
  {
    id: "s7",
    name: "Résidence Almadies",
    zone: "Almadies",
    agentsNeeded: 3,
    agentsPresent: 3,
  },
  {
    id: "s8",
    name: "CBAO Indépendance",
    zone: "Plateau",
    agentsNeeded: 4,
    agentsPresent: 4,
  },
];

export const SUPERVISION_AGENTS: SupervisionAgent[] = [
  {
    id: "a1",
    name: "Modou Faye",
    initials: "MF",
    site: "Port Autonome de Dakar",
    status: "alerte",
    note: "Immobile depuis 25 min",
    x: 13,
    y: 46,
    ping: 8,
  },
  {
    id: "a2",
    name: "Awa Diagne",
    initials: "AD",
    site: "Ambassade de France",
    status: "poste",
    x: 11,
    y: 43.5,
    ping: 34,
  },
  {
    id: "a3",
    name: "Cheikh Ndoye",
    initials: "CN",
    site: "Aéroport AIBD",
    status: "ronde",
    x: 20,
    y: 53,
    ping: 12,
  },
  {
    id: "a4",
    name: "Fatou Sarr",
    initials: "FS",
    site: "Siège Sonatel",
    status: "poste",
    x: 14,
    y: 48,
    ping: 51,
  },
  {
    id: "a5",
    name: "Ibrahima Ba",
    initials: "IB",
    site: "BICIS Plateau",
    status: "poste",
    x: 12.2,
    y: 45,
    ping: 27,
  },
  {
    id: "a6",
    name: "Ousmane Diop",
    initials: "OD",
    site: "Sea Plaza",
    status: "pause",
    x: 10,
    y: 46.5,
    ping: 68,
  },
  {
    id: "a7",
    name: "Mariama Sow",
    initials: "MS",
    site: "Résidence Almadies",
    status: "poste",
    x: 9,
    y: 42.5,
    ping: 40,
  },
  {
    id: "a8",
    name: "Abdou Kane",
    initials: "AK",
    site: "CBAO Indépendance",
    status: "ronde",
    x: 13,
    y: 47.5,
    ping: 9,
  },
  {
    id: "a9",
    name: "Aïda Ndiaye",
    initials: "AN",
    site: "Ambassade des USA",
    status: "poste",
    x: 11.6,
    y: 42,
    ping: 22,
  },
  {
    id: "a10",
    name: "Serigne Fall",
    initials: "SF",
    site: "BOA Thiès",
    status: "poste",
    x: 22,
    y: 46,
    ping: 44,
  },
  {
    id: "a11",
    name: "Khadija Ba",
    initials: "KB",
    site: "Préfecture Saint-Louis",
    status: "ronde",
    x: 20,
    y: 23,
    ping: 15,
  },
  {
    id: "a12",
    name: "Pape Guèye",
    initials: "PG",
    site: "Hôtel Saly (Mbour)",
    status: "pause",
    x: 18,
    y: 57,
    ping: 73,
  },
  {
    id: "a13",
    name: "Lamine Cissé",
    initials: "LC",
    site: "AIBD — zone fret",
    status: "alerte",
    note: "Sortie de zone détectée",
    x: 20.6,
    y: 54,
    ping: 6,
  },
];

const AGENTS_ROSTER = [
  "Modou Faye",
  "Awa Diagne",
  "Cheikh Ndoye",
  "Fatou Sarr",
  "Ibrahima Ba",
  "Ousmane Diop",
  "Mariama Sow",
  "Abdou Kane",
  "Aïda Ndiaye",
  "Serigne Fall",
  "Khadija Ba",
  "Pape Guèye",
  "Lamine Cissé",
  "Bineta Thiam",
  "Alioune Sène",
];

export const SHIFTS: Shift[] = AGENTS_ROSTER.flatMap((agent, i) =>
  Array.from({ length: 5 }, (_, day) => ({
    id: `sh-${i}-${day}`,
    agent,
    site: SITES[(i + day) % SITES.length].name,
    day,
    start: day % 2 === 0 ? "07:00" : "19:00",
    end: day % 2 === 0 ? "19:00" : "07:00",
    type: (day % 2 === 0 ? "jour" : "nuit") as Shift["type"],
  })),
);

export const ATTENDANCE: Attendance[] = AGENTS_ROSTER.slice(0, 12).map(
  (agent, i) => ({
    id: `att-${i}`,
    agent,
    site: SITES[i % SITES.length].name,
    date: "2026-07-03",
    checkIn: i === 4 ? "07:22" : i === 9 ? null : "06:58",
    checkOut: null,
    status: i === 9 ? "absent" : i === 4 ? "retard" : "present",
  }),
);

export const PAYSLIPS: Payslip[] = AGENTS_ROSTER.map((agent, i) => {
  const gross = 165000 + (i % 5) * 12000;
  const ipres = Math.round(gross * 0.056);
  const css = Math.round(gross * 0.036);
  const ir = Math.round(gross * 0.05);
  return {
    id: `ps-${i}`,
    agent,
    role: i % 6 === 0 ? "Chef de poste" : "Agent de sécurité",
    gross,
    ipres,
    css,
    ir,
    net: gross - ipres - css - ir,
    days: 26 - (i % 3),
  };
});

export const CANDIDATES: Candidate[] = [
  {
    id: "cd1",
    name: "Samba Ndiaye",
    initials: "SN",
    role: "Agent de sécurité",
    stage: "recus",
    experience: "3 ans",
    rating: 4,
    source: "Site web",
  },
  {
    id: "cd2",
    name: "Rokhaya Diallo",
    initials: "RD",
    role: "Agent de sécurité",
    stage: "recus",
    experience: "1 an",
    rating: 3,
    source: "Recommandation",
  },
  {
    id: "cd3",
    name: "Malick Sow",
    initials: "MS",
    role: "Chef de poste",
    stage: "preselection",
    experience: "6 ans",
    rating: 5,
    source: "LinkedIn",
  },
  {
    id: "cd4",
    name: "Coumba Faye",
    initials: "CF",
    role: "Agent de sécurité",
    stage: "preselection",
    experience: "2 ans",
    rating: 4,
    source: "Site web",
  },
  {
    id: "cd5",
    name: "Ibou Sarr",
    initials: "IS",
    role: "Agent cynophile",
    stage: "entretien",
    experience: "4 ans",
    rating: 4,
    source: "Agence",
  },
  {
    id: "cd6",
    name: "Ndeye Gueye",
    initials: "NG",
    role: "Agent de sécurité",
    stage: "entretien",
    experience: "5 ans",
    rating: 5,
    source: "Recommandation",
  },
  {
    id: "cd7",
    name: "Oumar Ba",
    initials: "OB",
    role: "Superviseur",
    stage: "test",
    experience: "8 ans",
    rating: 5,
    source: "LinkedIn",
  },
  {
    id: "cd8",
    name: "Fatima Cissé",
    initials: "FC",
    role: "Agent de sécurité",
    stage: "embauche",
    experience: "3 ans",
    rating: 4,
    source: "Site web",
  },
  {
    id: "cd9",
    name: "Babacar Ndour",
    initials: "BN",
    role: "Agent de sécurité",
    stage: "embauche",
    experience: "2 ans",
    rating: 4,
    source: "Agence",
  },
];

export const INTERVIEWS: Interview[] = [
  {
    id: "it1",
    candidate: "Ibou Sarr",
    role: "Agent cynophile",
    date: "2026-07-04",
    time: "10:00",
    interviewer: "Moussa Diop",
    mode: "présentiel",
  },
  {
    id: "it2",
    candidate: "Ndeye Gueye",
    role: "Agent de sécurité",
    date: "2026-07-04",
    time: "14:30",
    interviewer: "Moussa Diop",
    mode: "présentiel",
  },
  {
    id: "it3",
    candidate: "Oumar Ba",
    role: "Superviseur",
    date: "2026-07-05",
    time: "11:00",
    interviewer: "M. Diallo",
    mode: "téléphone",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Talkie-walkie Motorola",
    category: "Communication",
    price: 45000,
    stock: 24,
    threshold: 10,
  },
  {
    id: "p2",
    name: "Uniforme complet (veste + pantalon)",
    category: "Tenue",
    price: 28000,
    stock: 60,
    threshold: 20,
  },
  {
    id: "p3",
    name: "Rangers de sécurité",
    category: "Tenue",
    price: 22000,
    stock: 8,
    threshold: 15,
  },
  {
    id: "p4",
    name: "Lampe torche tactique",
    category: "Équipement",
    price: 12000,
    stock: 40,
    threshold: 12,
  },
  {
    id: "p5",
    name: "Détecteur de métaux portable",
    category: "Équipement",
    price: 85000,
    stock: 6,
    threshold: 5,
  },
  {
    id: "p6",
    name: "Gilet pare-balles niveau II",
    category: "Protection",
    price: 180000,
    stock: 0,
    threshold: 3,
  },
  {
    id: "p7",
    name: "Matraque télescopique",
    category: "Équipement",
    price: 15000,
    stock: 32,
    threshold: 10,
  },
  {
    id: "p8",
    name: "Casquette Dakar Sécurité",
    category: "Tenue",
    price: 6000,
    stock: 90,
    threshold: 25,
  },
  {
    id: "p9",
    name: "Badge magnétique",
    category: "Accès",
    price: 3500,
    stock: 150,
    threshold: 40,
  },
  {
    id: "p10",
    name: "Bâton lumineux de signalisation",
    category: "Signalisation",
    price: 4500,
    stock: 18,
    threshold: 20,
  },
];

export const RECEIPTS: Receipt[] = [
  {
    id: "rc1",
    ref: "REC-0231",
    time: "08:12",
    items: 3,
    total: 95000,
    method: "Espèces",
  },
  {
    id: "rc2",
    ref: "REC-0232",
    time: "09:34",
    items: 1,
    total: 45000,
    method: "Wave",
  },
  {
    id: "rc3",
    ref: "REC-0233",
    time: "10:05",
    items: 5,
    total: 128000,
    method: "Orange Money",
  },
  {
    id: "rc4",
    ref: "REC-0234",
    time: "11:20",
    items: 2,
    total: 34000,
    method: "Espèces",
  },
  {
    id: "rc5",
    ref: "REC-0235",
    time: "12:47",
    items: 4,
    total: 74000,
    method: "Wave",
  },
];

export const TICKETS: Ticket[] = [
  {
    id: "tk1",
    ref: "TIC-0091",
    title: "Portique détecteur HS",
    site: "Aéroport AIBD",
    criticality: "critique",
    stage: "ouvert",
    opened: "2026-07-02",
    equipment: "Portique zone fret",
  },
  {
    id: "tk2",
    ref: "TIC-0090",
    title: "Caméra télésurveillance figée",
    site: "Port Autonome de Dakar",
    criticality: "haute",
    stage: "encours",
    opened: "2026-07-01",
    equipment: "Caméra Môle 3",
  },
  {
    id: "tk3",
    ref: "TIC-0089",
    title: "Badge d'accès non reconnu",
    site: "BICIS Plateau",
    criticality: "normale",
    stage: "encours",
    opened: "2026-06-30",
    equipment: "Lecteur entrée B",
  },
  {
    id: "tk4",
    ref: "TIC-0088",
    title: "Éclairage parking défaillant",
    site: "Sea Plaza",
    criticality: "basse",
    stage: "attente",
    opened: "2026-06-28",
    equipment: "Projecteur P2",
  },
  {
    id: "tk5",
    ref: "TIC-0087",
    title: "Talkie-walkie hors service",
    site: "Siège Sonatel",
    criticality: "normale",
    stage: "resolu",
    opened: "2026-06-26",
    equipment: "TW-14",
  },
  {
    id: "tk6",
    ref: "TIC-0086",
    title: "Barrière automatique bloquée",
    site: "Résidence Almadies",
    criticality: "haute",
    stage: "resolu",
    opened: "2026-06-24",
    equipment: "Barrière entrée",
  },
];

export const INTERVENTIONS: Intervention[] = [
  {
    id: "in1",
    ref: "INT-0142",
    site: "Siège Sonatel",
    agent: "Ibrahima Sow",
    date: "2026-06-26",
    summary: "Remplacement talkie-walkie TW-14",
    status: "terminee",
    durationMin: 45,
  },
  {
    id: "in2",
    ref: "INT-0141",
    site: "Résidence Almadies",
    agent: "Ibrahima Sow",
    date: "2026-06-24",
    summary: "Déblocage barrière automatique",
    status: "terminee",
    durationMin: 90,
  },
  {
    id: "in3",
    ref: "INT-0143",
    site: "Aéroport AIBD",
    agent: "Ibrahima Sow",
    date: "2026-07-04",
    summary: "Diagnostic portique zone fret",
    status: "planifiee",
    durationMin: 120,
  },
];

export const PUBLICATIONS: Publication[] = [
  {
    id: "pb1",
    title: "Recrutement : 10 agents de sécurité",
    channel: "LinkedIn",
    date: "2026-07-05",
    status: "planifie",
  },
  {
    id: "pb2",
    title: "Sécurisation du Port Autonome",
    channel: "Facebook",
    date: "2026-07-07",
    status: "planifie",
  },
  {
    id: "pb3",
    title: "Nos équipes cynophiles en action",
    channel: "Instagram",
    date: "2026-07-09",
    status: "brouillon",
  },
  {
    id: "pb4",
    title: "Certification APSAD obtenue",
    channel: "Site web",
    date: "2026-06-28",
    status: "publie",
    engagement: 342,
  },
  {
    id: "pb5",
    title: "Interview du Directeur Général",
    channel: "LinkedIn",
    date: "2026-06-24",
    status: "publie",
    engagement: 518,
  },
  {
    id: "pb6",
    title: "Journée mondiale de la sécurité",
    channel: "Facebook",
    date: "2026-06-20",
    status: "publie",
    engagement: 276,
  },
];

export const IMAGE_ALERTS: ImageAlert[] = [
  {
    id: "al1",
    source: "Facebook — avis client",
    excerpt: "Retard de l'agent à l'ouverture ce matin au Sea Plaza…",
    sentiment: "négatif",
    date: "2026-07-02",
  },
  {
    id: "al2",
    source: "Google Reviews",
    excerpt: "Équipe très professionnelle au Port Autonome, merci !",
    sentiment: "positif",
    date: "2026-07-01",
  },
];

export const COMPANIES: Company[] = [
  {
    id: "co1",
    name: "Dakar Sécurité",
    city: "Dakar",
    plan: "Enterprise",
    seats: 52,
    mrr: 450000,
    status: "actif",
    since: "2024-01-01",
  },
  {
    id: "co2",
    name: "Téranga Guard",
    city: "Thiès",
    plan: "Pro",
    seats: 28,
    mrr: 220000,
    status: "actif",
    since: "2024-05-12",
  },
  {
    id: "co3",
    name: "Sahel Protection",
    city: "Saint-Louis",
    plan: "Pro",
    seats: 22,
    mrr: 220000,
    status: "actif",
    since: "2024-08-03",
  },
  {
    id: "co4",
    name: "Baobab Security",
    city: "Dakar",
    plan: "Starter",
    seats: 9,
    mrr: 90000,
    status: "essai",
    since: "2026-06-20",
  },
  {
    id: "co5",
    name: "Almadies Vigil",
    city: "Dakar",
    plan: "Enterprise",
    seats: 61,
    mrr: 450000,
    status: "actif",
    since: "2023-11-15",
  },
  {
    id: "co6",
    name: "Casamance Gardiennage",
    city: "Ziguinchor",
    plan: "Starter",
    seats: 12,
    mrr: 90000,
    status: "suspendu",
    since: "2025-02-10",
  },
];

export const TASKS: Task[] = [
  {
    id: "t1",
    title: "Valider la paie de juin",
    owner: "M. Diallo",
    due: "2026-07-05",
    priority: "haute",
    done: false,
  },
  {
    id: "t2",
    title: "Renouveler le contrat Port Autonome",
    owner: "Aïda Ba",
    due: "2026-07-10",
    priority: "haute",
    done: false,
  },
  {
    id: "t3",
    title: "Relancer l'Ambassade de France",
    owner: "Fatou Sarr",
    due: "2026-07-04",
    priority: "haute",
    done: false,
  },
  {
    id: "t4",
    title: "Réunion planning hebdomadaire",
    owner: "Cheikh Guèye",
    due: "2026-07-06",
    priority: "moyenne",
    done: false,
  },
  {
    id: "t5",
    title: "Commander gilets pare-balles",
    owner: "Awa N’Diaye",
    due: "2026-07-08",
    priority: "moyenne",
    done: false,
  },
  {
    id: "t6",
    title: "Entretien candidat superviseur",
    owner: "Moussa Diop",
    due: "2026-07-05",
    priority: "moyenne",
    done: false,
  },
  {
    id: "t7",
    title: "Clôturer la caisse du jour",
    owner: "Awa N’Diaye",
    due: "2026-07-03",
    priority: "basse",
    done: true,
  },
];

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    title: "Facture en retard",
    detail: "FAC-2025-041 impayée depuis 32 jours",
    tone: "danger",
    at: "2026-07-03T08:10:00",
    read: false,
  },
  {
    id: "n2",
    title: "Contrat à renouveler",
    detail: "CTR-2025-007 — Port Autonome expire dans 12 jours",
    tone: "warning",
    at: "2026-07-03T07:40:00",
    read: false,
  },
  {
    id: "n3",
    title: "Alerte terrain",
    detail: "Modou Faye immobile depuis 25 min au Port",
    tone: "danger",
    at: "2026-07-03T09:02:00",
    read: false,
  },
  {
    id: "n4",
    title: "Paie soumise",
    detail: "La paie de juin attend votre validation (Niveau 2)",
    tone: "info",
    at: "2026-07-02T18:20:00",
    read: true,
  },
  {
    id: "n5",
    title: "Nouveau devis signé",
    detail: "DEV-2026-028 — Clinique du Cap (1 200 000 FCFA)",
    tone: "success",
    at: "2026-07-02T15:05:00",
    read: true,
  },
];

/* Aggregated series for the dashboard chart. */
export const REVENUE_SERIES = [
  { month: "Jan", revenus: 9800000, depenses: 7100000 },
  { month: "Fév", revenus: 10200000, depenses: 7400000 },
  { month: "Mar", revenus: 10800000, depenses: 6900000 },
  { month: "Avr", revenus: 11300000, depenses: 7600000 },
  { month: "Mai", revenus: 11900000, depenses: 7850000 },
  { month: "Juin", revenus: 12450000, depenses: 8050000 },
];
